name: "Regression Testing using local provided PAT"
on:
  workflow_dispatch:

jobs:
  regression-local-pat:
    name: Regression Testing with local PAT
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          path: ghas-metrics-report
      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_USING_ACT: "true"
        with:
          repo: "hm-demo"
          org: "advanced-security-demo"
          features: "dependabot, code-scanning, secret-scanning"
          frequency: "daily"
          output-format: "json, pdf, issues"
      # - name: upload GHAS metrics report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ghas-metrics-report
      #     path: ghas-metrics-report/dist/report.json
